begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
set local role service_role;
select lives_ok($$insert into public.assets values ('REGTEST') on conflict do nothing$$, 'trusted service registers catalog asset');
select lives_ok($$insert into public.assets values ('REGTEST') on conflict do nothing$$, 'repeat registration is idempotent');
select throws_ok($$update public.assets set symbol = 'OTHER' where symbol = 'REGTEST'$$, '42501', null, 'registration cannot update catalog');
select throws_ok($$delete from public.assets where symbol = 'REGTEST'$$, '42501', null, 'registration cannot delete catalog');
select throws_ok($$insert into public.curated_assets values ('REGTEST')$$, '42501', null, 'service has no curation privilege');
select throws_ok($$select * from public.watchlist_items$$, '42501', null, 'service has no personal data access');
select throws_ok($$insert into private.admin_users values ('22222222-2222-4222-8222-222222222222')$$, '42501', null, 'service cannot promote users');
reset role;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}', true);
select lives_ok($$insert into public.watchlist_items (symbol) values ('REGTEST')$$, 'owner saves newly registered asset');
select is((select count(*) from public.curated_assets where symbol = 'REGTEST'), 0::bigint, 'registration does not curate');
select throws_ok($$insert into public.curated_assets values ('REGTEST')$$, '42501', null, 'owner still cannot curate');
select throws_ok($$insert into public.assets values ('BYPASS')$$, '42501', null, 'owner cannot bypass server validation');
select set_config('request.jwt.claims', '{"sub":"33333333-3333-4333-8333-333333333333","role":"authenticated"}', true);
select is((select count(*) from public.watchlist_items where symbol = 'REGTEST'), 0::bigint, 'another user cannot read new watchlist item');
reset role;
select * from finish();
rollback;
