export const privacyUpdated = 'September 25, 2026';
export const privacyEmail = 'ianrholdeman@gmail.com';
export const privacySections = [
  { title: 'Private price alerts', text: 'If you use alerts, Supabase stores your account-owned rules, evaluation state, and 30-day alert history with per-entry read status. Rules remain until deleted; deleting a rule does not erase its recent history. Account deletion removes live rules, history and delivery subscriptions. Optional notifications use an installation-specific preference and short-lived duplicate-prevention identifiers in browser storage. Installed Android background push stores a private subscription endpoint and encryption keys on the server, tied to your account and sign-in session. A browser push service transports encrypted, opaque event identifiers; the app checks authorization again before retrieving private notification content. Push-service acceptance does not guarantee display. Sending a push test stores only the latest test identifier and request/consumption times for that installation, replaced by the next test or removed with its subscription. Up to ten push installations per account are supported. Turning notifications off or signing out disables delivery on this installation without deleting history or changing other devices. If offline, local delivery is disabled and remote revocation is retried when the app reconnects. Minimal revocation credentials may remain in separate browser storage until that succeeds. Delivery attempts expire after 15 minutes; history expires after 30 days and is removed during subsequent evaluation cleanup. No email, analytics or behavioral presence tracking is used for alerts.' },
  { title: 'Information and use', text: 'Public pages do not require an account. Google sign-in provides account identity and profile information to Supabase Auth. The application uses your account ID, display name and saved symbols to operate sign-in and your private watchlist. It does not use analytics, advertising, paid subscriptions or behavioral profiling, and does not sell personal information or share it for targeted advertising.' },
  { title: 'Services and requests', text: 'Google Cloud Run hosts the application in Oregon (us-west1). Supabase processes authentication, watchlist and alert records in Oregon (AWS us-west-2). Private Google Cloud Storage in Oregon holds sanitized project test evidence, not your watchlist. Yahoo receives market symbols and search text through the application server. Your browser requests ticker logos directly from Parqet, which receives the requested symbol and network information. Infrastructure and authentication services process request metadata and may retain security logs and backups. External links open services governed by their own privacy practices.' },
  { title: 'Browser storage', text: 'The browser stores sign-in credentials and temporary sign-in verification data. The browser also stores your light or dark appearance preference when you choose one. Otherwise, the application uses your device’s appearance. This setting stays in this browser and is not sent to the application server. It remains after sign-out or account deletion; clearing site storage removes it. The app also stores a small offline connection-help page and its supporting scripts in this browser. This offline cache contains no account data, market prices or test evidence and remains after sign-out or account deletion; clearing site storage removes it. Market information is cached in memory; downloaded resources and visited URLs may remain in browser caches and history. Clearing site storage signs you out locally. The application does not change its behavior in response to Do Not Track or Global Privacy Control signals; it does not conduct the advertising or profiling described above.' },
  { title: 'Retention and deletion', text: 'Watchlist entries remain until you remove them or delete your account. Account deletion removes the live authentication identity, watchlist, alert rules/history/subscriptions and any app admin assignment. Shared asset records remain. Google Cloud operational logs are retained for 30 days; required audit logs for 400 days. Ordinary CI artifacts and snapshot caches have 90-day retention; a separately published historical test archive remains until deliberate replacement or removal. These test records contain no visitor watchlists. Deletion does not remove your Google account, browser history, or records retained separately in provider logs and backups. Other provider retention follows their settings and policies.' },
  { title: 'Requests', text: 'You can review and change your watchlist or delete your account in the application. For access, correction, deletion or privacy questions, email the contact below. Identity may need to be verified before account information is disclosed or changed. Messages are used to address the request and retained as needed for that purpose and applicable obligations. Do not email passwords or sign-in tokens.' },
  { title: 'Children and updates', text: 'This application is not directed at children under 13. Contact the operator if you believe such a child has provided personal information; the report will be reviewed and inappropriate collection addressed. Changes to this notice will be posted here with an updated date. Material changes to data use will be identified before they take effect.' },
] as const;
