export const privacyUpdated = 'September 8, 2026';
export const privacyEmail = 'ianrholdeman@gmail.com';
export const privacySections = [
  { title: 'Information and use', text: 'Public pages do not require an account. Google sign-in provides account identity and profile information to Supabase Auth. The application uses your account ID, display name and saved symbols to operate sign-in and your private watchlist. It does not use analytics, advertising, subscriptions or behavioral profiling, and does not sell personal information or share it for targeted advertising.' },
  { title: 'Services and requests', text: 'Supabase processes authentication and watchlist records. Yahoo receives market symbols and search text through the application server. Your browser requests ticker logos directly from Parqet, which receives the requested symbol and network information. Infrastructure and authentication services process request metadata and may retain security logs and backups. External links open services governed by their own privacy practices.' },
  { title: 'Browser storage', text: 'The browser stores sign-in credentials and temporary sign-in verification data. The browser also stores your light or dark appearance preference when you choose one. Otherwise, the application uses your device’s appearance. This setting stays in this browser and is not sent to the application server. It remains after sign-out or account deletion; clearing site storage removes it. Market information is cached in memory; downloaded resources and visited URLs may remain in browser caches and history. Clearing site storage signs you out locally. The application does not change its behavior in response to Do Not Track or Global Privacy Control signals; it does not conduct the advertising or profiling described above.' },
  { title: 'Retention and deletion', text: 'Watchlist entries remain until you remove them or delete your account. Account deletion removes the live authentication identity, watchlist and any app admin assignment. Shared asset records remain. Deletion does not remove your Google account, browser history, or records retained separately in provider logs and backups. Retention of those records depends on provider settings and policies.' },
  { title: 'Requests', text: 'You can review and change your watchlist or delete your account in the application. For access, correction, deletion or privacy questions, email the contact below. Identity may need to be verified before account information is disclosed or changed. Messages are used to address the request and retained as needed for that purpose and applicable obligations. Do not email passwords or sign-in tokens.' },
  { title: 'Children and updates', text: 'This application is not directed at children under 13. Contact the operator if you believe such a child has provided personal information; the report will be reviewed and inappropriate collection addressed. Changes to this notice will be posted here with an updated date. Material changes to data use will be identified before they take effect.' },
] as const;
